// Copyright 2026 The Magma Authors.
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.
//
// CDNi Logging proto per draft-ietf-cdni-logging-extensions
// Field names follow SVTA naming convention:
//   cs- = client→server, sc- = server→client, s- = server, c- = client
//   x_tc_ = Traffic Control extensions (not in IETF spec)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: cdni_log.proto

package cdnilog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CDNILogService_StreamLogs_FullMethodName      = "/magma.cdn.CDNILogService/StreamLogs"
	CDNILogService_SubmitLogBatch_FullMethodName  = "/magma.cdn.CDNILogService/SubmitLogBatch"
	CDNILogService_SubmitLogRecord_FullMethodName = "/magma.cdn.CDNILogService/SubmitLogRecord"
)

// CDNILogServiceClient is the client API for CDNILogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CDNILogService for log streaming and collection
type CDNILogServiceClient interface {
	StreamLogs(ctx context.Context, in *LogStreamRequest, opts ...grpc.CallOption) (CDNILogService_StreamLogsClient, error)
	SubmitLogBatch(ctx context.Context, in *CDNILogBatch, opts ...grpc.CallOption) (*LogAck, error)
	SubmitLogRecord(ctx context.Context, in *CDNILogRecord, opts ...grpc.CallOption) (*LogAck, error)
}

type cDNILogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCDNILogServiceClient(cc grpc.ClientConnInterface) CDNILogServiceClient {
	return &cDNILogServiceClient{cc}
}

func (c *cDNILogServiceClient) StreamLogs(ctx context.Context, in *LogStreamRequest, opts ...grpc.CallOption) (CDNILogService_StreamLogsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CDNILogService_ServiceDesc.Streams[0], CDNILogService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &cDNILogServiceStreamLogsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CDNILogService_StreamLogsClient interface {
	Recv() (*CDNILogRecord, error)
	grpc.ClientStream
}

type cDNILogServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *cDNILogServiceStreamLogsClient) Recv() (*CDNILogRecord, error) {
	m := new(CDNILogRecord)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cDNILogServiceClient) SubmitLogBatch(ctx context.Context, in *CDNILogBatch, opts ...grpc.CallOption) (*LogAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogAck)
	err := c.cc.Invoke(ctx, CDNILogService_SubmitLogBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cDNILogServiceClient) SubmitLogRecord(ctx context.Context, in *CDNILogRecord, opts ...grpc.CallOption) (*LogAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogAck)
	err := c.cc.Invoke(ctx, CDNILogService_SubmitLogRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CDNILogServiceServer is the server API for CDNILogService service.
// All implementations must embed UnimplementedCDNILogServiceServer
// for forward compatibility
//
// CDNILogService for log streaming and collection
type CDNILogServiceServer interface {
	StreamLogs(*LogStreamRequest, CDNILogService_StreamLogsServer) error
	SubmitLogBatch(context.Context, *CDNILogBatch) (*LogAck, error)
	SubmitLogRecord(context.Context, *CDNILogRecord) (*LogAck, error)
	mustEmbedUnimplementedCDNILogServiceServer()
}

// UnimplementedCDNILogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCDNILogServiceServer struct {
}

func (UnimplementedCDNILogServiceServer) StreamLogs(*LogStreamRequest, CDNILogService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedCDNILogServiceServer) SubmitLogBatch(context.Context, *CDNILogBatch) (*LogAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLogBatch not implemented")
}
func (UnimplementedCDNILogServiceServer) SubmitLogRecord(context.Context, *CDNILogRecord) (*LogAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLogRecord not implemented")
}
func (UnimplementedCDNILogServiceServer) mustEmbedUnimplementedCDNILogServiceServer() {}

// UnsafeCDNILogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CDNILogServiceServer will
// result in compilation errors.
type UnsafeCDNILogServiceServer interface {
	mustEmbedUnimplementedCDNILogServiceServer()
}

func RegisterCDNILogServiceServer(s grpc.ServiceRegistrar, srv CDNILogServiceServer) {
	s.RegisterService(&CDNILogService_ServiceDesc, srv)
}

func _CDNILogService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CDNILogServiceServer).StreamLogs(m, &cDNILogServiceStreamLogsServer{ServerStream: stream})
}

type CDNILogService_StreamLogsServer interface {
	Send(*CDNILogRecord) error
	grpc.ServerStream
}

type cDNILogServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *cDNILogServiceStreamLogsServer) Send(m *CDNILogRecord) error {
	return x.ServerStream.SendMsg(m)
}

func _CDNILogService_SubmitLogBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CDNILogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDNILogServiceServer).SubmitLogBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDNILogService_SubmitLogBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDNILogServiceServer).SubmitLogBatch(ctx, req.(*CDNILogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _CDNILogService_SubmitLogRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CDNILogRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CDNILogServiceServer).SubmitLogRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CDNILogService_SubmitLogRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CDNILogServiceServer).SubmitLogRecord(ctx, req.(*CDNILogRecord))
	}
	return interceptor(ctx, in, info, handler)
}

// CDNILogService_ServiceDesc is the grpc.ServiceDesc for CDNILogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CDNILogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "magma.cdn.CDNILogService",
	HandlerType: (*CDNILogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitLogBatch",
			Handler:    _CDNILogService_SubmitLogBatch_Handler,
		},
		{
			MethodName: "SubmitLogRecord",
			Handler:    _CDNILogService_SubmitLogRecord_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _CDNILogService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cdni_log.proto",
}
